#FOR DEVELOPMENT
services:
  gym-telegram-bot:
    build: .
    environment:
      DATABASE_PATH: /app/data/gym_bot.sqlite3
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?Set TELEGRAM_BOT_TOKEN before starting the bot}
      TELEGRAM_CONTACT_NAME: ${TELEGRAM_CONTACT_NAME:? TELEGRAM_CONTACT_NAME environment variable wasn't provided}
    # For more convenient work with database during development.
    volumes:
      - ./data:/app/data
      # include during development/tests for more convenient access to assets
      # also look at COPY command in dockerfile
      # - ./assets:/app/assets
    working_dir: /app
    restart: unless-stopped

# FOR SERVER
# services:
#   gym-bot:
      ## use prebuilt image from github
#     image: ghcr.io/lopushand/gym-telegram-bot:latest
#     restart: unless-stopped
#     environment:
#       TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?Required}
#       TELEGRAM_CONTACT_NAME: ${TELEGRAM_CONTACT_NAME:?Required}
#       DATABASE_PATH: /app/data/gym_bot.sqlite3
#     volumes:
#       - gym_bot_data:/app/data

# volumes:
#   gym_bot_data: